ws_woodstack_home:
    path:  /
    defaults: { _controller: WSWoodstackBundle:Wood:index, page: 1 }
    requirements:
       page: \d*

ws_woodstack_login:
    path:    /login
    defaults: { _controller:WSWoodstackBundle:Security:login }
    requirements:
      id: \d+

ws_woodstack_register:
    path:   /register
    defaults: { _controller:WSWoodstackBundle:Registration:register }
    requirements:
      id: \d+

ws_woodstack_client:
    path:    /client
    defaults:  { _controller:WSWoodstackBundle:Client:client }
    requirements:
      id: \d+

ws_woodstack_navbar:
    path:    /Navigation
    defaults: { _controller:WSWoodstackBundle:Navbar:navbar, page:1 }
    requirements:
      id: \d+
