# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
       FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
       ROLE_ADMIN:      ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
       fos_userbundle:
         id: fos_user.user_provider.username

    firewalls:
       main:
           pattern: ^/
           form_login:
              provider: fos_userbundle
              login_path: /woodstack/login
              check_path: /woodstack/login_check
              csrf_provider: security.csrf.token_manager
              always_use_default_target_path: true
              default_target_path: /woodstack
             # success_handler: ws_woodstack.component.authentication.handler.login_success_handler

           logout:   
                 path:   /woodstack/logout
                 target: /woodstack
                # success_handler: ws_woodstack.component.authentication.handler.logout_success_handler
           anonymous:  true
       

    access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTYCATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers